# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-23 22:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NutData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_cd', models.CharField(max_length=2)),
                ('deriv_cd', models.CharField(max_length=4)),
                ('ref_ndb_no', models.CharField(max_length=5)),
                ('add_nutr_mark', models.CharField(max_length=1)),
                ('stat_cmt', models.CharField(max_length=10)),
                ('addmod_date', models.CharField(max_length=10)),
                ('cc', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='NutrDef',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nutr_no', models.IntegerField(db_index=True)),
                ('units', models.CharField(max_length=7)),
                ('tagname', models.CharField(max_length=20)),
                ('nutr_desc', models.CharField(max_length=60)),
                ('num_dec', models.CharField(max_length=1)),
            ],
        ),
        migrations.AddField(
            model_name='nutdata',
            name='nutr_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutr.NutrDef'),
        ),
    ]
