# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0007_auto_20170603_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datsrcln',
            name='ndb_no',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='datsrcln',
            name='nutr_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutr.NutrDef'),
        ),
    ]
