# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 20:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0011_auto_20170603_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datsrcln',
            name='datasrc_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutr.DataSrc'),
        ),
    ]
