# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-03 21:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0012_auto_20170603_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datsrcln',
            name='nutr_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nutr.NutData'),
        ),
    ]
