# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0014_epacolo'),
    ]

    operations = [
        migrations.AddField(
            model_name='epacolo',
            name='lati',
            field=models.DecimalField(decimal_places=6, default=4.55, max_digits=9),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='epacolo',
            name='lat',
            field=models.CharField(max_length=50),
        ),
    ]
