# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0015_auto_20170605_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epacolo',
            name='cdate',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='epacolo',
            name='udate',
            field=models.CharField(max_length=10),
        ),
    ]
