# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0016_auto_20170605_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epacolo',
            name='long',
            field=models.CharField(max_length=10),
        ),
    ]
