# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutr', '0017_auto_20170605_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epacolo',
            name='ham',
            field=models.CharField(max_length=3),
        ),
    ]
